# docker compose versionとしての書き方のあれ
version: "3.8"

# 利用する コンテナ 一覧
services:
  # Serverless Frameworkのコマンドを実行する用の環境
  serverless:
    # 管理コンテナ名
    container_name: ${APP_NAME}-serverless
    # Dockerファイルにて 定義
    build: 
      context: ./docker/serverless
    working_dir: /app
    # 場所
    volumes:
      - ./serverless-src/:/app
    # envファイルの ロード
    env_file:
      - ./docker/serverless/.env.dev
    # 利用ポート
    ports:
        # 一旦 フロントエンド vite使う感じで
        - ${API_PORT:-3000}:3000
    # 常時起動
    tty: True
    # ログ
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"